---
#  This workflow checks if vars and secrets are present and fails if one is empty.
#  It should be included as a first step in all the workflows.
name: Check vars and secrets
on:
  workflow_call:

jobs:
  main:
    name: Check available vars and secrets
    runs-on: ubuntu-20.04
    steps:
      - name: Check vars
        run: |
          if [[ \
            -z '${{ vars.ECR_PUBLIC_HOST }}' || \
            -z '${{ vars.ECR_PUBLIC_REGISTRY }}' || \
            -z '${{ vars.KUSTOMIZE_VERSION }}'
          ]]; then
            echo '!!! Some repository variables are either missing or empty.'
            echo '!!! Please check either repository or organization settings.'
            exit 1
          fi

      - name: Check secrets
        run: |
          if [[ \
            -z '${{ secrets.AWS_MAINNET_ACCESS_KEY_ID }}' || \
            -z '${{ secrets.AWS_MAINNET_SECRET_ACCESS_KEY }}' || \
            -z '${{ secrets.AUTOCOMMIT_AUTHOR }}' || \
            -z '${{ secrets.AUTOCOMMIT_EMAIL }}' || \
            -z '${{ secrets.CI_GH_TOKEN }}' || \
            -z '${{ secrets.REPO_ARGOCD_APPS_NAME }}'
          ]]; then
            echo '!!! Some repository secrets are either missing or empty.'
            echo '!!! Please check either repository or organization settings.'
            exit 1
          fi
